# Generated by Django 6.0.5 on 2026-05-29 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.topic'),
            preserve_default=False,
        ),
    ]
